// apps/web/src/lib/components/ui/button/button.svelte
<script lang="ts" module>
  import { cn, type WithElementRef } from '$lib/utils.js';
  import { resolve } from '$app/paths';
  import { toPath } from '$lib/utils';
  import type { HTMLAnchorAttributes, HTMLButtonAttributes } from 'svelte/elements';
  import { type VariantProps, tv } from 'tailwind-variants';

  export const buttonVariants = tv({
    base: "focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive inline-flex shrink-0 items-center justify-center gap-2 rounded-md text-sm font-medium whitespace-nowrap transition-all outline-none focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 aria-disabled:pointer-events-none aria-disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90 shadow-xs',
        destructive:
          'bg-destructive hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60 text-white shadow-xs',
        outline:
          'bg-background hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50 border shadow-xs',
        secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80 shadow-xs',
        ghost: 'hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50',
        link: 'text-primary underline-offset-4 hover:underline'
      },
      size: {
        default: 'h-9 px-4 py-2 has-[>svg]:px-3',
        sm: 'h-8 gap-1.5 rounded-md px-3 has-[>svg]:px-2.5',
        lg: 'h-10 rounded-md px-6 has-[>svg]:px-4',
        icon: 'size-9',
        'icon-sm': 'size-8',
        'icon-lg': 'size-10'
      }
    },
    defaultVariants: {
      variant: 'default',
      size: 'default'
    }
  });

  export type ButtonVariant = VariantProps<typeof buttonVariants>['variant'];
  export type ButtonSize = VariantProps<typeof buttonVariants>['size'];

  export type ButtonProps = WithElementRef<HTMLButtonAttributes> &
    WithElementRef<HTMLAnchorAttributes> & {
      variant?: ButtonVariant;
      size?: ButtonSize;
    };
</script>

<script lang="ts">
  let {
    class: className,
    variant = 'default',
    size = 'default',
    ref = $bindable(null),
    href = undefined,
    type = 'button',
    disabled,
    children,
    ...restProps
  }: ButtonProps = $props();
</script>

{#if href}
  <a
    bind:this={ref}
    data-slot="button"
    class={cn(buttonVariants({ variant, size }), className)}
    href={resolve(toPath(disabled ? '' : (href ?? '')))}
    aria-disabled={disabled}
    role={disabled ? 'link' : undefined}
    tabindex={disabled ? -1 : undefined}
    {...restProps}
  >
    {@render children?.()}
  </a>
{:else}
  <button
    bind:this={ref}
    data-slot="button"
    class={cn(buttonVariants({ variant, size }), className)}
    {type}
    {disabled}
    {...restProps}
  >
    {@render children?.()}
  </button>
{/if}

// src/components/ui/button.tsx
import Link from 'next/link';
import { ButtonHTMLAttributes, DetailedHTMLProps } from 'react';
import { LoaderIcon } from '../icons/loader';

const variantStyles = {
  fill: 'bg-calypso text-white hover:bg-calypso-400 focus:bg-calypso-600 disabled:bg-neutral-300 disabled:text-neutral-500',
  outline: 'border border-calypso text-calypso hover:bg-calypso-100 dark:hover:bg-calypso-900 dark:border-calypso-900 focus:bg-calypso-200 disabled:border-calypso-300 disabled:text-calypso-300 dark:disabled:border-calypso-900 dark:disabled:text-calypso-900 disabled:hover:bg-transparent dark:disabled:hover:bg-transparent',
  shades: 'bg-light text-calypso hover:bg-calypso-100 dark:bg-dark dark:hover:bg-calypso-900 disabled:border-calypso-300 disabled:text-calypso-300 dark:disabled:border-calypso-900 dark:disabled:text-calypso-900 disabled:hover:bg-transparent dark:disabled:hover:bg-transparent',
  text: 'text-calypso hover:text-calypso-400 focus:text-calypso-600 disabled:text-calypso-300'
};

const sizeStyles = {
  xs: 'px-3 py-2 text-xs',
  sm: 'px-4 py-2 text-sm',
  md: 'px-4 py-2 text-base',
  lg: 'px-6 py-3 text-base',
  xl: 'px-6 py-4 text-lg'
};

export interface ButtonProps extends DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement> {
	children: React.ReactNode;
	variant?: keyof typeof variantStyles;
	size?: keyof typeof sizeStyles;
	isLoading?: boolean;
	isDisabled?: boolean;
	leftIcon?: React.ReactNode;
	rightIcon?: React.ReactNode;
	href?: string;
}

export default function Button({
  children,
  variant = 'fill',
  size = 'md',
  isLoading = false,
  isDisabled = false,
  leftIcon,
  rightIcon,
  href,
  ...props
}: ButtonProps) {
  const className = 'inline-flex items-center justify-center gap-2 rounded-lg font-medium transition-colors duration-200 focus:outline-none disabled:cursor-not-allowed';

  const { type = 'button', ...restProps } = props;

  if (typeof children === 'string') {
    restProps.title = restProps.title || children.toString();
  }

  if (href) {
    return (
      <Link
        href={href}
        className={`${className} ${variantStyles[variant]} ${sizeStyles[size]} ${restProps.className}`}
        title={restProps.title}
        rel="noopener noreferrer"
      >
        {isLoading && (
          <LoaderIcon className="mr-2 h-4 w-4 animate-spin" />
        )}
        {!isLoading && leftIcon && (
          <>{leftIcon}</>
        )}
        {children}
        {!isLoading && rightIcon && (
          <>{rightIcon}</>
        )}
      </Link>
    );
  }

  return (
    <button
      type={type}
      disabled={isDisabled || isLoading}
      {...restProps}
      className={`${className} ${variantStyles[variant]} ${sizeStyles[size]} ${restProps.className}`}
    >
      {isLoading && (
        <LoaderIcon className="mr-2 h-4 w-4 animate-spin" />
      )}
      {!isLoading && leftIcon && (
        <>{leftIcon}</>
      )}
      {children}
      {!isLoading && rightIcon && (
        <>{rightIcon}</>
      )}
    </button>
  );
}
